import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Create Selling",
  description: "Generated by create next app",
  keywords: ["selling", "expansive", "luxary"],
  authors: [{ name: "Chim SainaIna" }],
  applicationName: "Next Fullstack Gen1",
  openGraph: {
    title: "Car Selling",
    images: [
      "https://i.pinimg.com/736x/79/ed/5b/79ed5b78e7f0683f7e78f34cae93440e.jpg",
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <body>{children}</body>;
}
