import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by create next app",
  keywords: ["selling", "expansive", "luxary"],
  authors: [{ name: "Chim SainaIna" }],
  applicationName: "Next Fullstack Gen1",
  openGraph: {
    title: "About Page",
    images: [
      "https://i.pinimg.com/736x/59/00/50/59005053957274ad71359d55622ae45a.jpg",
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <body>{children}</body>;
}
