import type { Metadata } from "next";
import "./globals.css";
import localfont from "next/font/local";
import { FooterComponent } from "@/components/(landing)/nav/FooterComponent";
import React from "react";

import { NavbarComponent } from "@/components/(landing)/nav/NavbarComponent";

export const metadata: Metadata = {
  title: "Create Selling",
  description: "Generated by create next app",
  keywords: ["selling", "expansive", "luxary"],
  authors: [{ name: "Chim SainaIna" }],
  applicationName: "Next Fullstack Gen1",
  openGraph: {
    title: "Car Selling",
    images: [
      "https://i.pinimg.com/736x/79/ed/5b/79ed5b78e7f0683f7e78f34cae93440e.jpg",
    ],
  },
};

// kantumruy_font
const kantumruy_font = localfont({
  src: "../../public/fonts/KantumruyPro-SemiBold.ttf",
  variable: "--font-kantumruy",
  display: "swap",
  preload: true,
  fallback: ["sans"],
});

// lexend_font
const lexend_font = localfont({
  src: "../../public/fonts/Lexend-Regular.ttf",
  variable: "--font-lexend",
  display: "swap",
});

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${kantumruy_font.variable} ${lexend_font.variable}`}
    >
      <body>
        <NavbarComponent />

        {children}
        {modal}
        {/* <h1 lang="km">សួស្តី</h1> */}
        <FooterComponent />
      </body>
    </html>
  );
}
