import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Product Page",
  description: "Generated by create next app",
  keywords: ["selling", "expansive", "luxary"],
  authors: [{ name: "Chim SainaIna" }],
  applicationName: "Next Fullstack Gen1",
  openGraph: {
    title: "Product Page",
    images: [
      "https://i.pinimg.com/1200x/9e/f9/de/9ef9de4c5209b8d55ad5dc829f2c219a.jpg",
    ],
  },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
