import { Suspense } from "react";
import "../globals.css";

import StyledComponentsRegistry from "@/lib/registry";
import BlogListSkeleton from "@/components/Skeleton/BlogSkeleton";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog Page",
  description: "Generated by create next app",
  keywords: ["selling", "expansive", "luxary"],
  authors: [{ name: "Chim SainaIna" }],
  applicationName: "Next Fullstack Gen1",
  openGraph: {
    title: "Blog Page",
    images: [
      "https://i.pinimg.com/736x/d5/2a/34/d52a347abcab6f39d5024aa944dc0c64.jpg",
    ],
  },
};
export default function BlogLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex justify-center items-center">
      <StyledComponentsRegistry>
        <Suspense fallback={<BlogListSkeleton />}>{children}</Suspense>
      </StyledComponentsRegistry>
    </div>
  );
}
